# Generated by Django 4.1.4 on 2022-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='aplicaciones/static/img/', verbose_name='Imagen'),
        ),
    ]
